# Generated by Django 5.2.8 on 2025-11-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="first_message",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата первого сообщения"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="stop_mailing",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_body",
            field=models.TextField(verbose_name="Тело письма"),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="comment",
            field=models.TextField(verbose_name="Комментарий"),
        ),
    ]
