# Generated by Django 5.2.8 on 2025-11-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailing_first_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logmailing",
            name="run_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время попытки"
            ),
        ),
        migrations.AlterField(
            model_name="logmailing",
            name="server_answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="logmailing",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("success", "Успешно"), ("unsuccess", "Не успешно")],
                null=True,
                verbose_name="Статус отправки",
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
    ]
