# Generated by Django 5.2.8 on 2025-11-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_logmailing_run_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logmailing",
            name="run_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата и время попытки"
            ),
        ),
    ]
