# Generated by Django 5.2.8 on 2025-11-22 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_logmailing_run_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logmailing",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing",
                to="mailing.mailing",
                verbose_name="Рассылка",
            ),
        ),
    ]
