# Generated by Django 5.2.8 on 2025-11-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0010_alter_message_options_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["message_subject"],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
    ]
